FEATURE-RELEASE:support for actionJSON Photoshop API
adobe/adobe-photoshop-api-sdk pull request #24
Opened 2023-06-05 23:22 UTC by nbelofastow

Adobe introduced actionJSON service, which allows for execution of Photoshop actions in JSON format. See more details https://developer.adobe.com/photoshop/photoshop-api-docs/api/#tag/Photoshop/operation/actionJSON

## Description

- Bumped up @adobe/aio-lib-photoshop-api version 
- Added a sample code for actionJson API

## Motivation and Context

Since actionJSON supports Photoshop actions in JSON format, which is plain text, it offers more flexibility for Photoshop API users and allows for easy integration of Photoshop API with their workflows.

## How Has This Been Tested?

- Tested manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [  ] All new and existing tests passed.

2023-06-05 23:29 UTC, kmikawa requested changes

2023-06-05 23:29 UTC, kmikawa commented on src/sample/psapi/14_applyPhotoshopActionsJson.js
> +      ],
Can you use a human readable format?

2023-06-05 23:56 UTC, nbelofastow commented on src/sample/psapi/14_applyPhotoshopActionsJson.js
> +      ],
done

2023-06-06 18:15 UTC, kmikawa commented
lgtm. thanks.

2023-06-06 18:32 UTC, merged